### ISSUE TITLE
nextant not found (installation fails)

### ISSUE THREAD

**Issue by ghost** [jirislav/mailinabox#1]
Hello @jirislav 

Thanks for your work but i am running in a problem. Just tried your fork on a clean ubuntu 16.04. First run (setup/start.sh) gets through but leaves me without a running nginx. Second run (as recommended) fails with:

```
Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
creating sqlite db

FAILED: sudo -u www-data php /usr/local/lib/owncloud/console.php app:enable nextant
-----------------------------------------
nextant not found
-----------------------------------------
root@craftedmail:~/mailinabox#
```

any ideas?

thanks and cheers

**Comment by jirislav** [comment]
Hi & thanks for trying this fork out!

I must disappoint you for the moment because I'm not going to have much free time anytime soon to take a look into your installation failure :( The reason is that I have to create a Dockerfile, which I can use to test new features - including installation. This task isn't trivial.

But I may recommend you now, to just skip installing nextant by simply commenting out those problematic lines. Nextant is not any crucial feature for mail & cloud.

**Comment by jirislav** [comment]
Or feel free to find & fix a bug related to this error. You can then create a Pull Request so that I can merge it :)

**Comment by ghost** [comment]
Fixed with:

```
--- mailinabox/setup/owncloud.sh	2017-10-18 12:13:29.694697358 +0200
+++ mailinabox.setup.complete/setup/owncloud.sh	2017-10-18 11:27:09.891154081 +0200
@@ -36,7 +36,7 @@
 
 InstallSolr() {
 
-	local SOLR_VERSION=6.6.0
+	local SOLR_VERSION=6.6.2
 	echo "Installing solr version $SOLR_VERSION"
 
 	# Also prepare for nextant with solr
@@ -44,7 +44,8 @@
 
 	local SOLR_PATH=/usr/local/lib/solr
 	local SOLR_DATA=$STORAGE_ROOT/solr/data
-	wget_verify ftp://mirror.hosting90.cz/apache/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz 88add027c90adfdaaaeb335aa02394bfd7015f18 /tmp/solr.tgz
+        wget http://archive.apache.org/dist/lucene/solr/6.6.2/solr-6.6.2.tgz
+        mv solr-6.6.2.tgz /tmp/solr.tgz
 	tar xf /tmp/solr.tgz -C /usr/local/lib/
 	mv /usr/local/lib/solr-${SOLR_VERSION} $SOLR_PATH
```

**Comment by stefanheijnen** [comment]
I have the same error, but your fix didn't resolve the error. Did you change anything else?

**Comment by ghost** [comment]
Don't think so.

**Comment by lbr88** [comment]
I ran into this bug. First run of the installer just ended somewhere after installing solr with no error message. then i reran the mailinbox installer and it then came out with the nextant missing error. will try to rollback to my pre-install snapshot and try your fix

**Comment by madera17** [comment]
@stefanheijnen Fix didn't work for me either.

**Comment by stefanheijnen** [comment]
@madera17 I've commented out the references to nextant to get it working. The function is only needed when you want to search text within all of your JPGs, PNGs, PDFs, Office documents, etc..

See https://paste.ubuntu.com/25938380/

**Comment by PaulRitzkat** [comment]
Installing nextant and solr (6.6.**2**) manually worked, no clue why the setup script doesn't, I just copied the parts from the owncloud script... I had to manually edit the nextcloud config too (login and such where missing). Everything else works fine 👍

**Comment by jirislav** [comment]
Guys, thank you all for your throughout testing & debugging!

I've incorporated your fixes into `v0.25-ubuntu16` tag, so you may use this to install `mailinabox` without nextant:
```bash
git fetch --all
git checkout v0.25-ubuntu16
INSTALL_NEXTCLOUD=no setup/start.sh
```

Or, if you would like to give nextant/solr another try, you may just usually run:
```bash
git fetch --all
git checkout v0.25-ubuntu16
setup/start.sh
```

Closing this issue for now :) Feel free to reopen if something goes wrong, but according to your feedback, it shouldn't.
